### ISSUE TITLE
Makefile missing

### ISSUE THREAD

**Issue by stappersg** [lancastr/rust-dhcp#1]
Hi,

Here some who loves to try rust-lang and wants to play with DHCP.

I do miss a makefile or another file that describes the build steps.

Please document how to build this project.

Cheers
Geert Stappers

**Comment by stappersg** [comment]
With `cargo build` there is an error on misspelled `ifconfig`:
```
    Updating crates.io index
    Updating git repository `https://github.com/glebpom/rust-netif`
error: failed to load source for a dependency on `ifcontrol`                                    

Caused by:
  Unable to update https://github.com/glebpom/rust-netif?rev=master
Caused by:
  failed to update submodule `ipconfig`

Caused by:
  invalid url `git@github.com:glebpom/ipconfig.git`: relative URL without a base
```
But I think that is an issue for https://github.com/glebpom/rust-netif?rev=master

**Comment by stappersg** [comment]
There is now pull request https://github.com/glebpom/rust-netif/pull/1

**Comment by glebpom** [comment]
Hi,

I'm not sure if it's the right repository to start playing with rust. Currently, it's not properly maintained, and we are not (yet) using it in a real product. 
Regarding the Makefile - typically rust ecosystem relies on `cargo`, please refer the documentation.
Feel free to create the PR with build process documented and examples in `README.md`

**Comment by stappersg** [comment]
Update: 
```
cargo build
```
and
```
cargo build  --examples
```
now work for me.

I even have played with  DHCP.

**Comment by stappersg** [comment]
#2 alllows to close this issue
